### ISSUE TITLE
FileNotFoundError when running `make duck_cloudfront` command

### ISSUE THREAD

**Issue by silentninja** [commoncrawl/whirlwind-python#10]
#### **Description**
Running the `make duck_cloudfront` command described in the README results in a `FileNotFoundError`. The error occurs in the duck.py script which is trying to read the  CC-MAIN-2024-22.warc.paths.gz which is not created yet

#### **Suggested Fix**
1. Add the  `CC-MAIN-2024-22.warc.paths.gz ` file to the repository as mentioned in the [makefile](https://github.com/commoncrawl/whirlwind-python/blob/da9c01ef31efa2e4f553cde343668640ef1d67d9/Makefile#L60)

**Comment by wumpus** [comment]
Thank you, I took your suggestion in a recent PR.
